# Generated by Django 5.2.3 on 2025-06-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "turno",
                    models.IntegerField(
                        choices=[(1, "Turno 1"), (2, "Turno 2"), (3, "Turno 3")]
                    ),
                ),
                ("numero_nota", models.CharField(max_length=50)),
                ("peso_nota", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
