# Generated by Django 5.2.3 on 2025-07-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notafiscal",
            old_name="numero_nota",
            new_name="tipo_veiculo",
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="nf",
            field=models.CharField(default="Nulo", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="qnt_pallet",
            field=models.CharField(default="0", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="un_origem",
            field=models.CharField(default="Nulo", max_length=4),
            preserve_default=False,
        ),
    ]
