# Generated by Django 5.2.3 on 2025-08-15 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0002_rename_numero_nota_notafiscal_tipo_veiculo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notafiscal",
            name="data",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
