# Generated by Django 5.2.3 on 2025-08-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0003_alter_notafiscal_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notafiscal",
            name="nf",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Número da Nota"
            ),
        ),
    ]
