# Generated by Django 5.2.3 on 2026-01-03 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0004_alter_notafiscal_nf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notafiscal",
            name="data",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="peso_nota",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Peso da Nota (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="qnt_pallet",
            field=models.PositiveSmallIntegerField(
                verbose_name="Quantidade de Pallets"
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="tipo_veiculo",
            field=models.CharField(max_length=50, verbose_name="Tipo de Veículo"),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="turno",
            field=models.IntegerField(
                choices=[(1, "Turno 1"), (2, "Turno 2"), (3, "Turno 3")],
                verbose_name="Turno",
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="un_origem",
            field=models.CharField(max_length=4, verbose_name="UN Origem"),
        ),
    ]
