# Generated by Django 5.2.3 on 2026-01-04 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0005_alter_notafiscal_data_alter_notafiscal_peso_nota_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notafiscal",
            name="data",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Data"
            ),
        ),
    ]
