# Generated by Django 5.2.3 on 2026-01-04 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport", "0010_alter_carga_carga"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleSeparacao",
            fields=[
                (
                    "lecom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="controle_separacao",
                        serialize=False,
                        to="transport.lecom",
                        verbose_name="Lecom",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Andamento", "Em Andamento"),
                            ("Concluido", "Concluído"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "inicio_separacao",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Início da Separação"
                    ),
                ),
                ("atribuida", models.BooleanField(default=False)),
                ("finalizado", models.BooleanField(default=False)),
                (
                    "outros_separadores",
                    models.CharField(
                        blank=True, default="Não informado", max_length=255
                    ),
                ),
                (
                    "conferente",
                    models.CharField(
                        blank=True, default="Não informado", max_length=100
                    ),
                ),
                ("resumo_conf", models.BooleanField(default=False)),
                ("resumo_motorista", models.BooleanField(default=False)),
                ("etiquetas_cds", models.BooleanField(default=False)),
                ("carga_gerada", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Controle de Separação",
                "verbose_name_plural": "Controles de Separação",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="SeparacaoCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField(verbose_name="SEQ da Carga")),
                (
                    "numero_transporte",
                    models.CharField(max_length=10, verbose_name="Número da Carga"),
                ),
                ("entregas", models.CharField(default="1", max_length=2)),
                ("mod", models.CharField(default="-", max_length=10)),
                ("resumo", models.CharField(default="1", max_length=2)),
                (
                    "ot",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Ordem de Transporte",
                    ),
                ),
                (
                    "entrega_box",
                    models.CharField(
                        blank=True, default="Não informado", max_length=3, null=True
                    ),
                ),
                ("seg", models.CharField(default="", max_length=10)),
                ("atribuida", models.BooleanField(default=False)),
                ("finalizada", models.BooleanField(default=False)),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="separacoes",
                        to="transport.carga",
                    ),
                ),
                (
                    "controle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargas",
                        to="expedicao.controleseparacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga em Separação",
                "verbose_name_plural": "Cargas em Separação",
                "ordering": ["seq"],
                "unique_together": {("controle", "seq")},
            },
        ),
    ]
