# Generated by Django 5.2.3 on 2025-08-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControleSeparacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("numero_transporte", models.CharField(max_length=50)),
                (
                    "ot",
                    models.CharField(max_length=50, verbose_name="Ordem de Transporte"),
                ),
                ("faturado", models.BooleanField(default=False)),
                ("separador_principal", models.CharField(blank=True, max_length=100)),
                ("outros_separadores", models.CharField(blank=True, max_length=255)),
                ("conferente", models.CharField(blank=True, max_length=100)),
                ("entrega_box", models.CharField(blank=True, max_length=100)),
                ("resumo_conf", models.BooleanField(default=False)),
                ("resumo_motorista", models.BooleanField(default=False)),
                ("etiquetas_cds", models.BooleanField(default=False)),
                (
                    "tipo_veiculo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3/4", "3/4"),
                            ("toco", "Toco"),
                            ("carreta", "Carreta"),
                            ("truck", "Truck"),
                            ("rodotrem", "Rodotrem"),
                            ("container", "Container"),
                            ("utilitario", "Utilitário"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inicio_separacao", models.TimeField(blank=True, null=True)),
                ("atribuida", models.BooleanField(default=False)),
                ("finalizado", models.BooleanField(default=False)),
            ],
        ),
    ]
