# Generated by Django 5.2.3 on 2025-08-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="controleseparacao",
            old_name="faturado",
            new_name="carga_gerada",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="separador_principal",
        ),
    ]
