# Generated by Django 5.2.3 on 2026-01-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controleseparacao",
            name="atribuida",
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="liberada",
            field=models.BooleanField(
                default=False, help_text="Só aparece no cenário quando True"
            ),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="inicio_separacao",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Início da Separação"
            ),
        ),
    ]
