# Generated by Django 5.2.3 on 2025-08-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0002_rename_faturado_controleseparacao_carga_gerada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleseparacao",
            name="destino",
            field=models.CharField(default="Destino desconhecido", max_length=150),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="data",
            field=models.DateField(verbose_name="Data da Carga"),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="numero_transporte",
            field=models.CharField(max_length=50, verbose_name="Número da Carga"),
        ),
    ]
