# Generated by Django 5.2.3 on 2026-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0002_remove_controleseparacao_atribuida_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleseparacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aguardando", "Aguardando"),
                    ("Andamento", "Em Andamento"),
                    ("Concluido", "Concluído"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
    ]
