# Generated by Django 5.2.3 on 2025-08-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0003_controleseparacao_destino_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleseparacao",
            name="entrega_box",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
