# Generated by Django 5.2.3 on 2026-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0003_alter_controleseparacao_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controleseparacao",
            options={"ordering": ["-criado_em"]},
        ),
        migrations.AlterModelOptions(
            name="separacaocarga",
            options={"ordering": ["seq"]},
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="inicio_separacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="liberada",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Aguardando", "Aguardando"),
                    ("Em Andamento", "Em Andamento"),
                    ("Concluido", "Concluído"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="separacaocarga",
            name="numero_transporte",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="separacaocarga",
            name="ot",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="separacaocarga",
            name="seq",
            field=models.PositiveIntegerField(),
        ),
    ]
