# Generated by Django 5.2.3 on 2025-08-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0004_alter_controleseparacao_entrega_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleseparacao",
            name="entrega_box",
            field=models.CharField(
                blank=True, default="Não informado", max_length=100, null=True
            ),
        ),
    ]
