# Generated by Django 5.2.3 on 2026-01-22 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0004_alter_controleseparacao_options_and_more"),
        ("transport", "0011_alter_veiculo_tipo_veiculo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controleseparacao",
            name="carga_gerada",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="conferente",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="etiquetas_cds",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="outros_separadores",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="resumo_conf",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="resumo_motorista",
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="lecom",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="controle_separacao",
                serialize=False,
                to="transport.lecom",
            ),
        ),
    ]
