# Generated by Django 5.2.3 on 2025-08-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0005_alter_controleseparacao_entrega_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleseparacao",
            name="conferente",
            field=models.CharField(blank=True, default="Não informado", max_length=100),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="outros_separadores",
            field=models.CharField(blank=True, default="Não informado", max_length=255),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="tipo_veiculo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3/4", "3/4"),
                    ("toco", "Toco"),
                    ("carreta", "Carreta"),
                    ("truck", "Truck"),
                    ("rodotrem", "Rodotrem"),
                    ("container", "Container"),
                    ("utilitario", "Utilitário"),
                ],
                default="Não informado",
                max_length=20,
            ),
        ),
    ]
