# Generated by Django 5.2.3 on 2026-01-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0005_remove_controleseparacao_carga_gerada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="separacaocarga",
            name="carga_gerada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="separacaocarga",
            name="conferente",
            field=models.CharField(
                blank=True, default="Não informado", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="separacaocarga",
            name="etiquetas_cds",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="separacaocarga",
            name="resumo_conf",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="separacaocarga",
            name="resumo_motorista",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="separacaocarga",
            name="separadores",
            field=models.CharField(
                blank=True, default="Não informado", max_length=10, null=True
            ),
        ),
    ]
