# Generated by Django 5.2.3 on 2026-01-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0006_separacaocarga_carga_gerada_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="separacaocarga",
            old_name="entrega_box",
            new_name="box",
        ),
        migrations.AddField(
            model_name="separacaocarga",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Em Andamento", "Em Andamento"),
                    ("Concluido", "Concluído"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="separacaocarga",
            name="conferente",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="separacaocarga",
            name="separadores",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
