# Generated by Django 5.2.3 on 2025-08-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0006_alter_controleseparacao_conferente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleseparacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pendente", "Pendente"),
                    ("Andamento", "Em Andamento"),
                    ("Concluido", "Concluído"),
                ],
                default="Pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="entrega_box",
            field=models.CharField(
                blank=True, default="Não informado", max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="numero_transporte",
            field=models.CharField(max_length=10, verbose_name="Número da Carga"),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="ot",
            field=models.CharField(max_length=10, verbose_name="Ordem de Transporte"),
        ),
    ]
