# Generated by Django 5.2.3 on 2025-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0007_controleseparacao_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleseparacao",
            name="entregas",
            field=models.CharField(default="1", max_length=2),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="lecom",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="mod",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="observacao",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="peso",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="resumo",
            field=models.CharField(default="1", max_length=2),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="uf",
            field=models.CharField(default="", max_length=2),
        ),
    ]
