# Generated by Django 5.2.3 on 2026-01-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0007_rename_entrega_box_separacaocarga_box_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="separacaocarga",
            name="separadores",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
