# Generated by Django 5.2.3 on 2025-08-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "expedicao",
            "0008_controleseparacao_entregas_controleseparacao_lecom_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="controleseparacao",
            name="m3",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="seg",
            field=models.CharField(default="", max_length=10),
        ),
    ]
