# Generated by Django 5.2.3 on 2026-01-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0008_alter_separacaocarga_separadores"),
    ]

    operations = [
        migrations.AddField(
            model_name="separacaocarga",
            name="inicio_separacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
