# Generated by Django 5.2.3 on 2026-02-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0009_separacaocarga_inicio_separacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="separacaocarga",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aguardando", "Aguardando"),
                    ("Em Andamento", "Em Andamento"),
                    ("Concluido", "Concluído"),
                ],
                default="Aguardando",
                max_length=20,
            ),
        ),
    ]
