# Generated by Django 5.2.3 on 2025-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0009_controleseparacao_m3_controleseparacao_seg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleseparacao",
            name="data",
            field=models.DateField(auto_now_add=True, verbose_name="Data da Carga"),
        ),
    ]
