# Generated by Django 5.2.3 on 2025-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0010_alter_controleseparacao_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleseparacao",
            name="destino",
            field=models.CharField(default="", max_length=150),
        ),
    ]
