# Generated by Django 5.2.3 on 2026-02-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0010_alter_separacaocarga_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleseparacao",
            name="data_carregamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="hora_carregamento",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[("Manhã", "Manhã"), ("Tarde", "Tarde"), ("Noite", "Noite")],
                max_length=10,
                null=True,
            ),
        ),
    ]
