# Generated by Django 5.2.3 on 2026-02-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0011_controleseparacao_data_carregamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="separacaocarga",
            name="box",
            field=models.CharField(blank=True, default="", max_length=3, null=True),
        ),
    ]
