# Generated by Django 5.2.3 on 2026-01-04 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0011_alter_controleseparacao_destino"),
        ("transport", "0010_alter_carga_carga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleseparacao",
            name="lecom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles",
                to="transport.lecom",
                verbose_name="Lecom",
            ),
        ),
    ]
