# Generated by Django 5.2.3 on 2026-01-04 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0012_alter_controleseparacao_lecom"),
        ("transport", "0010_alter_carga_carga"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controleseparacao",
            name="data",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="destino",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="entrega_box",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="entregas",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="m3",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="mod",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="numero_transporte",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="observacao",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="ot",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="peso",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="resumo",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="seg",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="tipo_veiculo",
        ),
        migrations.RemoveField(
            model_name="controleseparacao",
            name="uf",
        ),
        migrations.AddField(
            model_name="controleseparacao",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="lecom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles",
                to="transport.lecom",
            ),
        ),
        migrations.CreateModel(
            name="SeparacaoCarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entregas", models.CharField(default="1", max_length=2)),
                ("mod", models.CharField(default="-", max_length=10)),
                (
                    "numero_transporte",
                    models.CharField(max_length=10, verbose_name="Número da Carga"),
                ),
                ("resumo", models.CharField(default="1", max_length=2)),
                (
                    "ot",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Ordem de Transporte",
                    ),
                ),
                (
                    "entrega_box",
                    models.CharField(
                        blank=True, default="Não informado", max_length=3, null=True
                    ),
                ),
                ("seg", models.CharField(default="", max_length=10)),
                ("atribuida", models.BooleanField(default=False)),
                ("finalizada", models.BooleanField(default=False)),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transport.carga",
                    ),
                ),
                (
                    "controle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargas",
                        to="expedicao.controleseparacao",
                    ),
                ),
            ],
        ),
    ]
