# Generated by Django 5.2.3 on 2026-01-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedicao", "0013_remove_controleseparacao_data_and_more"),
        ("transport", "0010_alter_carga_carga"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controleseparacao",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Controle de Separação",
                "verbose_name_plural": "Controles de Separação",
            },
        ),
        migrations.AlterModelOptions(
            name="separacaocarga",
            options={
                "ordering": ["seq"],
                "verbose_name": "Carga em Separação",
                "verbose_name_plural": "Cargas em Separação",
            },
        ),
        migrations.AddField(
            model_name="separacaocarga",
            name="seq",
            field=models.PositiveIntegerField(default=1, verbose_name="SEQ da Carga"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="inicio_separacao",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Início da Separação"
            ),
        ),
        migrations.AlterField(
            model_name="controleseparacao",
            name="lecom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controles",
                to="transport.lecom",
                verbose_name="Lecom",
            ),
        ),
        migrations.AlterField(
            model_name="separacaocarga",
            name="carga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="separacoes",
                to="transport.carga",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="controleseparacao",
            unique_together={("lecom",)},
        ),
        migrations.AlterUniqueTogether(
            name="separacaocarga",
            unique_together={("controle", "seq")},
        ),
    ]
