# Generated by Django 5.2.3 on 2025-12-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecom", models.CharField(default="", max_length=10)),
                (
                    "carga",
                    models.CharField(max_length=10, verbose_name="Número da Carga"),
                ),
                ("seq", models.CharField(default="1", max_length=2)),
                ("destino", models.CharField(default="", max_length=150)),
                ("uf", models.CharField(default="", max_length=2)),
                (
                    "peso",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "m3",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "data",
                    models.DateField(auto_now_add=True, verbose_name="Data da Carga"),
                ),
                ("entregas", models.CharField(default="1", max_length=2)),
                ("mod", models.CharField(default="", max_length=10)),
                (
                    "observacao",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tipo_veiculo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3/4", "3/4"),
                            ("toco", "Toco"),
                            ("carreta", "Carreta"),
                            ("truck", "Truck"),
                            ("rodotrem", "Rodotrem"),
                            ("container", "Container"),
                            ("utilitario", "Utilitário"),
                        ],
                        default="Não informado",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Bloqueado", "Bloqueado"), ("liberado", "liberado")],
                        default="Bloqueado",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
