# Generated by Django 5.2.3 on 2025-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LecomGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecom", models.CharField(max_length=10, unique=True)),
                ("veiculo", models.CharField(blank=True, default="", max_length=100)),
                ("motorista", models.CharField(blank=True, default="", max_length=100)),
                (
                    "observacao",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("data", models.DateField(verbose_name="Data da Carga")),
            ],
        ),
        migrations.AlterField(
            model_name="transport",
            name="tipo_veiculo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3/4", "3/4"),
                    ("Toco", "Toco"),
                    ("Carreta", "Carreta"),
                    ("Truck", "Truck"),
                    ("Rodotrem", "Rodotrem"),
                    ("Container", "Container"),
                    ("Utilitario", "Utilitário"),
                ],
                default="Não informado",
                max_length=20,
            ),
        ),
    ]
