# Generated by Django 5.2.3 on 2025-12-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0002_lecomgroup_alter_transport_tipo_veiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="data",
            field=models.DateField(verbose_name="Data da Carga"),
        ),
    ]
