# Generated by Django 5.2.3 on 2025-12-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0003_alter_transport_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carga",
                    models.CharField(max_length=10, verbose_name="Número da Carga"),
                ),
                ("seq", models.PositiveIntegerField(blank=True, null=True)),
                ("total_entregas", models.CharField(default="1", max_length=2)),
                ("mod", models.CharField(default="", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="transport.carga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lecom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecom", models.CharField(default="", max_length=10)),
                ("destino", models.CharField(default="", max_length=150)),
                ("uf", models.CharField(default="", max_length=2)),
                (
                    "peso",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "m3",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("data", models.DateField(verbose_name="Data da Carga")),
                (
                    "observacao",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_veiculo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3/4", "3/4"),
                            ("Toco", "Toco"),
                            ("Carreta", "Carreta"),
                            ("Truck", "Truck"),
                            ("Rodotrem", "Rodotrem"),
                            ("Container", "Container"),
                            ("Utilitario", "Utilitário"),
                        ],
                        default="Não informado",
                        max_length=20,
                    ),
                ),
                (
                    "lecom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veiculo",
                        to="transport.lecom",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LecomGroup",
        ),
        migrations.DeleteModel(
            name="Transport",
        ),
        migrations.AddField(
            model_name="carga",
            name="lecom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargas",
                to="transport.lecom",
            ),
        ),
        migrations.AddField(
            model_name="mod",
            name="carga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mods",
                to="transport.carga",
            ),
        ),
    ]
