# Generated by Django 5.2.3 on 2025-12-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transport",
            "0004_carga_entrega_lecom_mod_veiculo_delete_lecomgroup_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lecom",
            name="status",
            field=models.CharField(
                choices=[("LIBERADO", "Liberado"), ("BLOQUEADO", "Bloqueado")],
                default="PENDENTE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lecom",
            name="destino",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="lecom",
            name="lecom",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="lecom",
            name="observacao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="lecom",
            name="uf",
            field=models.CharField(max_length=2),
        ),
    ]
