# Generated by Django 5.2.3 on 2025-12-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transport",
            "0005_lecom_status_alter_lecom_destino_alter_lecom_lecom_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecom",
            name="status",
            field=models.CharField(
                choices=[("LIBERADO", "Liberado"), ("BLOQUEADO", "Bloqueado")],
                default="Liberado",
                max_length=10,
            ),
        ),
    ]
