# Generated by Django 5.2.3 on 2025-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0006_alter_lecom_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecom",
            name="status",
            field=models.CharField(
                choices=[("LIBERADO", "Liberado"), ("BLOQUEADO", "Bloqueado")],
                default="BLOQUEADO",
                max_length=10,
            ),
        ),
    ]
