# Generated by Django 5.2.3 on 2025-12-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0007_alter_lecom_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carga",
            name="mod",
            field=models.CharField(default="-", max_length=10),
        ),
    ]
