# Generated by Django 5.2.3 on 2026-01-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0008_alter_carga_mod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecom",
            name="lecom",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
