# Generated by Django 5.2.3 on 2026-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0009_alter_lecom_lecom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carga",
            name="carga",
            field=models.CharField(
                default="1", max_length=10, verbose_name="Número da Carga"
            ),
        ),
    ]
