# Generated by Django 5.2.3 on 2026-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0010_alter_carga_carga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="tipo_veiculo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Utilitario", "Utilitário"),
                    ("Container", "Container"),
                    ("Bi-Truck", "Bi-Truck"),
                    ("Rodotrem", "Rodotrem"),
                    ("Carreta", "Carreta"),
                    ("Truck", "Truck"),
                    ("Toco", "Toco"),
                    ("3/4", "3/4"),
                ],
                default="Não informado",
                max_length=20,
            ),
        ),
    ]
