# Generated by Django 5.2.3 on 2026-01-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0011_alter_veiculo_tipo_veiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecom",
            name="status",
            field=models.CharField(
                choices=[("Liberado", "Liberado"), ("Bloqueado", "Bloqueado")],
                default="Bloqueado",
                max_length=10,
            ),
        ),
    ]
